# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConstitutionOfIndia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConstitutionOfIndia
 pod 'SideMenu'
 pod 'SDWebImage'

end
